name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  Release_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: do the job
        run: |
          cp webvirtcloud/settings.py.template webvirtcloud/settings.py
          grep "SECRET_KEY" webvirtcloud/settings.py | awk -F\" '{print NF-1}'
          sed -i "s/SECRET_KEY \= \"\"/SECRET_KEY = \"$(python3 conf/runit/secret_generator.py)\"/" webvirtcloud/settings.py
          docker build . --file Dockerfile --tag webvirtcloud:$(date +%s)
          docker images
      - name: push
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.io
          repository: madebug/webvirtcloud
          tags: latest
