name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  Release_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
#      - name: do something to the code
#        run: echo "Changed code" > text.txt
      - id: docker-publish
        name: Build image
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
            # Checkout the repository
            checkout: 'false'
            # Tag to override default Logic
            image_tag: latest
            # Use the SHA for the tag.  Overrides the default logic.
            use_sha: true
            # Docker org name.
            org_name: madebug
            # Name of the docker repository
            repo_name: # optional, default is 
            # Tag default branch with latest tag instead of branch name.
            use_latest: # optional, default is true
            # Docker user
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            # Docker password
            docker_password: ${{ secrets.DOCKER_TOKEN }}
            # Add a string of values to the end of the build command
            build_args: # optional
            # Specify the working directory that the docker build will be run in
            working-directory: .
      - run: |
          echo "Image Created:  ${{ env.image }}"
          echo "Tag Created: ${{ env.tag }}"
